// flow-typed signature: d3f4a323a95fde10c98f4be4bc3a9a7b
// flow-typed version: <<STUB>>/axios-cache-adapter_v^2.1.1/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'axios-cache-adapter'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'axios-cache-adapter' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'axios-cache-adapter/dist/cache' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/dist/cache.min' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/dist/cache.node' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/dist/cache.node.min' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/cache' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/config' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/exclude' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/index' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/limit' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/memory' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/request' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/response' {
  declare module.exports: any;
}

declare module 'axios-cache-adapter/src/serialize' {
  declare module.exports: any;
}

// Filename aliases
declare module 'axios-cache-adapter/dist/cache.js' {
  declare module.exports: $Exports<'axios-cache-adapter/dist/cache'>;
}
declare module 'axios-cache-adapter/dist/cache.min.js' {
  declare module.exports: $Exports<'axios-cache-adapter/dist/cache.min'>;
}
declare module 'axios-cache-adapter/dist/cache.node.js' {
  declare module.exports: $Exports<'axios-cache-adapter/dist/cache.node'>;
}
declare module 'axios-cache-adapter/dist/cache.node.min.js' {
  declare module.exports: $Exports<'axios-cache-adapter/dist/cache.node.min'>;
}
declare module 'axios-cache-adapter/src/cache.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/cache'>;
}
declare module 'axios-cache-adapter/src/config.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/config'>;
}
declare module 'axios-cache-adapter/src/exclude.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/exclude'>;
}
declare module 'axios-cache-adapter/src/index.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/index'>;
}
declare module 'axios-cache-adapter/src/limit.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/limit'>;
}
declare module 'axios-cache-adapter/src/memory.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/memory'>;
}
declare module 'axios-cache-adapter/src/request.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/request'>;
}
declare module 'axios-cache-adapter/src/response.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/response'>;
}
declare module 'axios-cache-adapter/src/serialize.js' {
  declare module.exports: $Exports<'axios-cache-adapter/src/serialize'>;
}
